reward:
  # --- 奖励权重 ---
  reward_at_goal: 300.0            # 到达目标
  penalty_at_collision: -300.0      # 碰撞
  reward_factor_approaching_goal: 5.0        # 靠近目标的比例系数
  penalty_elapsing_time: -0.5             # 每步时间惩罚
  penalty_stuck: -2.0            # 卡住惩罚
  reward_good_orientation: 2.0          # 好方向奖励
  penalty_in_safe_proximity: -1.0           # 安全距离内惩罚
  penalty_action_smoothness: -0.5